/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/articles": {
    get: operations["ArticlesController_getAll"];
    post: operations["ArticlesController_create"];
  };
  "/api/articles/by-id/{id}": {
    get: operations["ArticlesController_getOne"];
    delete: operations["ArticlesController_delete"];
    patch: operations["ArticlesController_update"];
  };
}

export interface components {
  schemas: {
    Article: { [key: string]: unknown };
    ArticlesDto: {
      title: string;
      description: string;
      /** Format: date-time */
      publishedAt: string;
      slug: string;
      body: string;
    };
  };
}

export interface operations {
  ArticlesController_getAll: {
    parameters: {};
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Article"][];
        };
      };
    };
  };
  ArticlesController_create: {
    parameters: {};
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["Article"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ArticlesDto"];
      };
    };
  };
  ArticlesController_getOne: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
    };
  };
  ArticlesController_delete: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: unknown;
    };
  };
  ArticlesController_update: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ArticlesDto"];
      };
    };
  };
}

export interface external {}
