/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/articles": {
    get: operations["ArticlesController_getAll"];
    post: operations["ArticlesController_create"];
  };
  "/api/articles/{slug}": {
    get: operations["ArticlesController_getOne"];
    put: operations["ArticlesController_update"];
    delete: operations["ArticlesController_delete"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    ArticleDto: {
      title: string;
      description: string;
      /** Format: date-time */
      publishedAt: string;
      slug: string;
      body: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export interface operations {

  ArticlesController_getAll: {
    responses: {
      200: {
        content: {
          "application/json": (components["schemas"]["ArticleDto"])[];
        };
      };
    };
  };
  ArticlesController_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ArticleDto"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["ArticleDto"];
        };
      };
    };
  };
  ArticlesController_getOne: {
    parameters: {
      path: {
        slug: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": (components["schemas"]["ArticleDto"])[];
        };
      };
      404: never;
    };
  };
  ArticlesController_update: {
    parameters: {
      path: {
        slug: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ArticleDto"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ArticleDto"];
        };
      };
      404: never;
    };
  };
  ArticlesController_delete: {
    parameters: {
      path: {
        slug: string;
      };
    };
    responses: {
      204: never;
      404: never;
    };
  };
}
